version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ${DOCKERFILE:-Dockerfile}
    container_name: whisper-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    environment:
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-""}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: ${GPU_COUNT:-0}
              capabilities: [gpu]
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: whisper-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
