from enum import Enum


class InputLanguage(str, Enum):
    ENGLISH = "en"
    PORTUGUESE = "pt"
    SPANISH = "es"
    FRENCH = "fr"
    GERMAN = "de"
    ITALIAN = "it"
    DUTCH = "nl"
    RUSSIAN = "ru"
    CHINESE = "zh"
    JAPANESE = "ja"
    KOREAN = "ko"
    ARABIC = "ar"
    TURKISH = "tr"
    POLISH = "pl"
    ROMANIAN = "ro"
    HUNGARIAN = "hu"
    GREEK = "el"
    CZECH = "cs"
    SLOVAK = "sk"
    UKRAINIAN = "uk"
    HINDI = "hi"
    THAI = "th"
    VIETNAMESE = "vi"
    INDONESIAN = "id"
    HEBREW = "he"
    SWEDISH = "sv"
    NORWEGIAN = "no"
    FINNISH = "fi"
    DANISH = "da"